"""Storage primitives."""

from personality_jelly.storage.database import create_database_engine, create_session_factory
from personality_jelly.storage.migrations import (
    CURRENT_SCHEMA_VERSION,
    MIGRATIONS,
    AppliedMigration,
    Migration,
    MigrationResult,
    MigrationStatus,
    ensure_database_ready,
    get_migration_status,
    migrate_database,
)
from personality_jelly.storage.orm import Base, create_all
from personality_jelly.storage.repositories import (
    AuditEventRepository,
    CanonClaimRepository,
    CharacterRepository,
    ClaimConflictRepository,
    ContextPackageRepository,
    ConversationRepository,
    CriticReportRepository,
    EvaluationCaseResultRepository,
    EvaluationRunRepository,
    EvidenceRefRepository,
    FailureCaseRepository,
    LLMRawOutputRepository,
    MemoryRepository,
    MessageRepository,
    PersonaVersionRepository,
    RetrievalEvaluationCaseResultRepository,
    RetrievalEvaluationRunRepository,
    SourceChunkRepository,
    SourceChunkEmbeddingRepository,
    SourceWorkRepository,
    UserRepository,
    WorkflowRunLinkRepository,
    WorkflowRunRepository,
)

__all__ = [
    "AuditEventRepository",
    "Base",
    "CURRENT_SCHEMA_VERSION",
    "CanonClaimRepository",
    "CharacterRepository",
    "ClaimConflictRepository",
    "ContextPackageRepository",
    "ConversationRepository",
    "CriticReportRepository",
    "EvaluationCaseResultRepository",
    "EvaluationRunRepository",
    "EvidenceRefRepository",
    "FailureCaseRepository",
    "LLMRawOutputRepository",
    "MemoryRepository",
    "MIGRATIONS",
    "AppliedMigration",
    "Migration",
    "MigrationResult",
    "MigrationStatus",
    "MessageRepository",
    "PersonaVersionRepository",
    "RetrievalEvaluationCaseResultRepository",
    "RetrievalEvaluationRunRepository",
    "SourceChunkRepository",
    "SourceChunkEmbeddingRepository",
    "SourceWorkRepository",
    "UserRepository",
    "WorkflowRunLinkRepository",
    "WorkflowRunRepository",
    "create_all",
    "create_database_engine",
    "create_session_factory",
    "ensure_database_ready",
    "get_migration_status",
    "migrate_database",
]

