"""Shared application-service bootstrap helpers.

This package is the boundary that CLI commands and future API adapters can both use for
orchestration concerns that do not belong in domain modules.
"""

from personality_jelly.application.bootstrap import (
    DatabaseResources,
    create_database_resources,
    resolve_database_url,
)
from personality_jelly.application.errors import NormalizedError, normalize_error
from personality_jelly.application.inspection import (
    BenchmarkModeDiagnostics,
    CharacterDetail,
    CharacterSummary,
    ClaimSummary,
    ContextPackageDetail,
    ContextPackageSummary,
    ConversationDetail,
    ConversationSummary,
    CriticReportDetail,
    CriticReportSummary,
    EvaluationCaseResultSummary,
    EvaluationRunDetail,
    EvaluationRunSummary,
    EvidenceRefSummary,
    ExpansionState,
    FailureCaseDetail,
    FailureCaseSummary,
    InspectionListResult,
    InspectionModel,
    LLMTraceDetail,
    LLMTraceSummary,
    LayeredSummary,
    LinkedId,
    MemorySummary,
    MessageSummary,
    OOCBenchmarkDiagnostics,
    PersonaVersionSummary,
    RetrievalBenchmarkDiagnostics,
    RetrievalEvaluationCaseResultSummary,
    RetrievalEvaluationRunDetail,
    RetrievalEvaluationRunSummary,
    SourceChunkDetail,
    SourceChunkSummary,
    SourceWorkSummary,
    UserSummary,
    get_character_detail,
    get_claim_detail,
    get_memory_detail,
    get_source_chunk_detail,
    list_claims,
    list_memories,
)
from personality_jelly.application.providers import (
    ModelRoleBundle,
    ProviderRoleBundle,
    build_turn_role_bundles,
    resolve_embedding_config,
    resolve_embedding_provider,
    resolve_roleplay_provider,
)

__all__ = [
    "BenchmarkModeDiagnostics",
    "CharacterDetail",
    "CharacterSummary",
    "ClaimSummary",
    "ContextPackageDetail",
    "ContextPackageSummary",
    "ConversationDetail",
    "ConversationSummary",
    "DatabaseResources",
    "EvaluationCaseResultSummary",
    "EvaluationRunDetail",
    "EvaluationRunSummary",
    "EvidenceRefSummary",
    "ExpansionState",
    "FailureCaseDetail",
    "FailureCaseSummary",
    "InspectionListResult",
    "InspectionModel",
    "LLMTraceDetail",
    "LLMTraceSummary",
    "LayeredSummary",
    "LinkedId",
    "MemorySummary",
    "MessageSummary",
    "ModelRoleBundle",
    "NormalizedError",
    "OOCBenchmarkDiagnostics",
    "PersonaVersionSummary",
    "ProviderRoleBundle",
    "RetrievalBenchmarkDiagnostics",
    "RetrievalEvaluationCaseResultSummary",
    "RetrievalEvaluationRunDetail",
    "RetrievalEvaluationRunSummary",
    "SourceChunkDetail",
    "SourceChunkSummary",
    "SourceWorkSummary",
    "UserSummary",
    "build_turn_role_bundles",
    "create_database_resources",
    "get_character_detail",
    "get_claim_detail",
    "get_memory_detail",
    "get_source_chunk_detail",
    "list_claims",
    "list_memories",
    "normalize_error",
    "resolve_database_url",
    "resolve_embedding_config",
    "resolve_embedding_provider",
    "resolve_roleplay_provider",
]
